name: Create Issue Branch

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create issue branch
      id: create_branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE=${{ github.event.issue.title }}

        # Convert ISSUE_TITLE to a branch-friendly format
        SAFE_TITLE=$(echo "$ISSUE_TITLE" | iconv -f utf-8 -t ascii//TRANSLIT | tr -cd '[:alnum:]-' | tr '[:space:]' '-')
        BRANCH_NAME="${ISSUE_NUMBER}-${SAFE_TITLE}"

        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git fetch origin
        git checkout -b "$BRANCH_NAME" origin/develop
        git push origin "$BRANCH_NAME"

    - name: Add comment to issue
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Branch [${{ github.event.issue.title }}] has been created: 
          ```
          ${{ env.BRANCH_NAME }}
          ```
